name: Build e Publish Image Container

on:
    workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Logar no registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Instalar o jq
        run: sudo apt-get install jq
  
      - name: Versão do package.json
        run: |
          VERSION=$(jq -r '.version' source/package.json)
          echo "VERS O DO PROJETO: $VERSION"

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build e Push da imagem
        uses: docker/build-push-action@v2.0.0
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/fexdelux/action-example-docker:$VERSION
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
