name: Run deploy - Staging

on:
    pull_request:
        branches: [ 'release/*' ]
        
jobs:
    run_deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
    build:
        needs: run_deploy
        uses: ./.github/workflows/flows/build-flow.yaml
        secrets: inherit
    tests:
        needs: run_deploy
        uses: ./.github/workflows/flows/test.yaml
        secrets: inherit
    converge:
        needs: run_deploy
        uses: ./.github/workflows/flows/converge.yaml
        secrets: inherit
    deploy_img_container:
        needs:
            - build
            - tests
            - converge
        uses: ./.github/workflows/flows/deploy-img-container.yaml
        secrets: inherit
    deploy_gitops:
        needs: deploy_img_container
        uses: ./.github/workflows/flows/deploy-gitops.yaml
        secrets: inherit
    notification:
        if: always()
        needs: deploy_gitops
        uses: ./.github/workflows/flows/notification.yaml
